#!/usr/bin/env bash
#Configure your Nginx server so that /redirect_me is redirecting to another page.
REDIR='rewrite ^/redirect_me$ /https://www.youtube.com/watch?v=QH2-TGUlwu4/$1 permanent;'
file='/etc/nginx/sites-available/default'
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo service nginx start
sudo sed -i "$REDIR" $file
sudo echo "Hello World!" | sudo tee /var/www/html/index.html
