#!/usr/bin/env bash
# Configure Nginx so that /redirect_me is redirecting to another page
REDIR="\\\tlocation /redirect_me {\n\t\t return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"
SRC="/etc/nginx/sites-available/default"
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo service nginx start
sudo sed -i "30i $REDIR" $SRC
sudo echo "Hello World!" | sudo tee /var/www/html/index.html
