#!/usr/bin/env bash
#Configure your Nginx server so that /redirect_me is redirecting to another page.
REDIR="\\\tlocation /redirect_me {\n\t\t return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"
file="/etc/nginx/sites-available/default"
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo service nginx start
sudo sed -i "$REDIR" $file
echo "Ceci n'est pas une page\n" >> /var/www/html/error_404.html
sed -i '40i\error_page 404 /error_404.html;' /etc/nginx/sites-available/default
sudo echo "Hello World!" | sudo tee /var/www/html/index.html
