#!/usr/bin/env bash
#Configure your Nginx server with custom 404 page.
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo service nginx start
sudo echo "Hello World!" | sudo tee /var/www/html/index.html
sudo sed -i "\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n" /etc/nginx/sites-available/default
sudo sed -i "\n\terror_page 404 /404error.html;\n\tlocation = /404error.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}\n" /usr/share/nginx/html/404error.html
sudo echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404error.html
sudo sed -i "\n\tadd_header X-Served-By $hostname;\n" /etc/nginx/sites-available/default
