#!/usr/bin/env bash
# install load balancer
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.6
sudo apt-get -y update
sudo apt-get -y install haproxy=1.6.\*
sudo echo -e "\nlisten www" >> /etc/haproxy/haproxy.cfg
sudo echo -e "\tbind :80" >> /etc/haproxy/haproxy.cfg
sudo echo -e "\tbalance roundrobin" >> /etc/haproxy/haproxy.cfg
sudo echo -e "\tserver 21316-web-01 35.173.36.123" >> /etc/haproxy/haproxy.cfg
sudo echo -e "\tserver gc-499-web-02-1554448076 3.237.39.37" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
