#!/usr/bin/env bash
# This script is displaying "Best School" 9 times plus "Hi" on the 2nd last loop.

a=0

while [ $a -lt 10 ]
do
	if [ $a -eq 9 ]
	then
		echo "Hi"
	fi	
	echo "Best School"
	(( a++ ))
done
