#!/usr/bin/env bash
# This script prints numbers 1-20, with additional message on iterations 4, 9 & 17

a=1

while [ $a -le 20 ]
do
	echo "$a"
	case $a in
		"4") echo "bad luck from China";;
		"9") echo "bad luck from Japan";;
		"17") echo "bad luck from Italy";;
	esac	
	(( a++ ))
done
